### ISSUE TITLE
documentation issue: cannot use the word 'IG' in Facebook App Display Name

### ISSUE THREAD

**Issue by jlahijani** [nbcommunication/InstagramBasicDisplayApi#16]
The documentation says:

> Give your app a Display Name. This cannot contain certain reserved words such as Instagram or Facebook. I recommend using something like IG Feed - ProcessWire Website.

But if you use 'IG' in the name, Facebook will come back with:

> Certain terms like "ig" are not allowed. For example, you may not use our trademarks or brand elements (including FB, Face, Book, Insta, Gram, and Rift) or any confusingly similar terms in your app name if such term is, or could be perceived as, a reference to Facebook or its brands. We ask that you only submit an app name appeal if you have reviewed all applicable policies and believe you are in compliance. Please note that we rarely grant app name appeals.

![2020-08-11_9-12-15](https://user-images.githubusercontent.com/4558/89921643-d3a9be80-dbb2-11ea-9bc4-2957f4854b6e.png)

**Comment by chriswthomson** [comment]
Ah, they must've changed this. My app is called that. I've pushed a change. Cheers.
